# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170331_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='hymn',
            name='chorus',
            field=models.TextField(default='Chorus...'),
        ),
    ]
